version: '3.8'

services:
  115-strm-web-test:
    
    build: .
    container_name: 115-strm-web-test
    volumes:
      - /Users/xianer/Documents/docker/115strmweb/strm:/app/strm
      - /Users/xianer/Documents/docker/115strmweb/logs:/app/logs
      - /Users/xianer/Documents/docker/115strmweb/config:/app/config

    ports:
      - "19080:18080"
    environment:
      - TZ=Asia/Shanghai
    restart: always